### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mncavieres** [fraserevans/speedystar#2]
Hello there, 

I am trying to install this package and it is failing due to a syntax error after running pip install ./ in the cloned directory. There seems to be a missing comma in line 6 of setup.py, see the error below. 

`pip install ./
Processing /Users/mncavieres/speedystar
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/mncavieres/speedystar/setup.py", line 6
          long_description='This package allows you to generate, propagate and observe mock populations of hypervelocity stars. Please see github.com/fraserevans/speedystar for a comphrehensive README and example executables.'
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: invalid syntax. Perhaps you forgot a comma?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
`

**Comment by fraserevans** [comment]
Hi Miguel,

Yes, there's a missing comma in line 6, sorry about that!

The package as a whole is outdated and the current version should be easier
to install. Give me the rest of the day and I should have the new one up on
github (probably not pip though).

Best,
Fraser

**Comment by mncavieres** [comment]
Hi Fraser,

Amazing! I will not post anymore issues in the current version then.

Best,
Manuel
________________________________
De: fraserevans ***@***.***>
Enviado: martes, 24 de septiembre de 2024 13:40
Para: fraserevans/speedystar ***@***.***>
Cc: Manuel Antonio Cavieres Carrera ***@***.***>; Author ***@***.***>
Asunto: Re: [fraserevans/speedystar] Installation Issue (Issue #2)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

Hi Miguel,

Yes, there's a missing comma in line 6, sorry about that!

The package as a whole is outdated and the current version should be easier
to install. Give me the rest of the day and I should have the new one up on
github (probably not pip though).

Best,
Fraser
